### ISSUE TITLE
Unhandled exception at installation

### ISSUE THREAD

**Issue by mintydan** [christineye/calibre-tts-ebook-viewer#2]
Hi Christine Ye,

Looks like a very useful plugin but
the zip won't install for me.
Any ideas?
Thanks 
mintydan

Here's the full error message:

calibre, version 2.54.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:/Users/admin/Downloads/lib01/lib03/calibre-tts-ebook-viewer-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.54 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: .... && Read MP3 AudioBook metadata
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 415, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 55, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 188, in load
  File "site-packages\calibre\customize\zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'C:/Users/admin/Downloads/lib01/lib03/calibre-tts-ebook-viewer-master.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by christineye** [comment]
Unfortunately, if you download the zip from Github it puts the files into a folder inside the zip, which calibre doesn't like.

A properly formatted zip can be found here:
https://www.mobileread.com/forums/showthread.php?p=3293126

I gotta figure out how to upload a separate download package to github to make it more convenient, but you can download from there for now.
