### ISSUE TITLE
ViewerPlugin is removed in the latest version of Calibre 

### ISSUE THREAD

**Issue by hariprasadraja** [christineye/calibre-tts-ebook-viewer#4]
Hi, 

Viewer plugin class is removed and it breaks the plugin getting installed in the modern caliber. please fix it. 

[https://github.com/kovidgoyal/calibre/commit/737bfa44cb719b057225ae528a583f4ace6b130c](https://github.com/kovidgoyal/calibre/commit/737bfa44cb719b057225ae528a583f4ace6b130c)

**Comment by christineye** [comment]
Calibre now has a built in TTS ability in the reader in latest versions, so I don't plan on updating this plugin further.
